services:
  mariadb:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: mogams99
      MARIADB_PASSWORD: tester777
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db_network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: mogams99
      POSTGRES_PASSWORD: tester777
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db_network

volumes:
  mariadb_data:
  postgres_data:

networks:
  db_network:
    driver: bridge